language: python
python:
 - 2.7
install:
  - pip install detox
script: detox
notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#armstrongcms"
